# This is a basic workflow to help you get started with Actions

name: Banco PingWord Backup Diario

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '0 3 * * *'
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  backup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Instalar PostgreSQL 18 Client
        run: sudo apt-get update
          sudo apt-get install -y wget gnupg2
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y postgresql-client-18

      - name: Executar Dump do Banco
        run: pg_dump "${{ secrets.DB_CONNECTION_STRING }}" > backup_render.sql

      - name: Salvar Backup como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: backup-do-dia-${{ github.run_id }}
          path: backup_render.sql
          retention-days: 30
